#include <stdio.h>
#include "logging.h"

static const char *TAG = "main";

// Embedded binary assets (generated by CMake target_add_binary_data)
extern const uint8_t web_ui_html_gz_start[] asm("_binary_web_ui_html_gz_start");
extern const uint8_t web_ui_html_gz_end[] asm("_binary_web_ui_html_gz_end");
extern const uint8_t recovery_html_gz_start[] asm("_binary_recovery_html_gz_start");
extern const uint8_t recovery_html_gz_end[] asm("_binary_recovery_html_gz_end");
extern const uint8_t icon_192_png_start[] asm("_binary_icon_192_png_start");
extern const uint8_t icon_192_png_end[] asm("_binary_icon_192_png_end");
extern const uint8_t icon_512_png_start[] asm("_binary_icon_512_png_start");
extern const uint8_t icon_512_png_end[] asm("_binary_icon_512_png_end");

extern "C" void app_main(void) {
    logging_init();
    LOG_INFO("Mitsubishi CN105 HomeKit Controller starting...");

    ESP_LOGI(TAG, "Embedded assets: web_ui=%d bytes, recovery=%d bytes, icon192=%d bytes, icon512=%d bytes",
        (int)(web_ui_html_gz_end - web_ui_html_gz_start),
        (int)(recovery_html_gz_end - recovery_html_gz_start),
        (int)(icon_192_png_end - icon_192_png_start),
        (int)(icon_512_png_end - icon_512_png_start));
}
