#include "web_server.h"
#include "json_utils.h"
#include "branding.h"
#include "wifi_manager.h"
#include "homekit_setup.h"
#include "logging.h"
#include "compat_arduino.h"
#include <cstring>
#include <cstdio>
#include <lwip/sockets.h>

static const char *TAG = "web";

// ── Embedded binary assets (generated by CMake target_add_binary_data) ──────
extern const uint8_t web_ui_html_gz_start[] asm("_binary_web_ui_html_gz_start");
extern const uint8_t web_ui_html_gz_end[]   asm("_binary_web_ui_html_gz_end");
extern const uint8_t recovery_html_gz_start[] asm("_binary_recovery_html_gz_start");
extern const uint8_t recovery_html_gz_end[]   asm("_binary_recovery_html_gz_end");
extern const uint8_t icon_192_png_start[] asm("_binary_icon_192_png_start");
extern const uint8_t icon_192_png_end[]   asm("_binary_icon_192_png_end");
extern const uint8_t icon_512_png_start[] asm("_binary_icon_512_png_start");
extern const uint8_t icon_512_png_end[]   asm("_binary_icon_512_png_end");

// ── Global instance ──────────────────────────────────────────────────────────
WebUI webUI;

// ══════════════════════════════════════════════════════════════════════════════
// HTTP handler: GET /  (serve embedded gzipped HTML)
// ══════════════════════════════════════════════════════════════════════════════

esp_err_t WebUI::sendGzipPage(httpd_req_t *req, const uint8_t *data, size_t len) {
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
    httpd_resp_send(req, (const char *)data, len);
    return ESP_OK;
}

esp_err_t WebUI::handleRoot(httpd_req_t *req) {
    // If AP fallback is active, check if client is on the AP subnet (192.168.4.x)
    if (webUI._apMode) {
        int fd = httpd_req_to_sockfd(req);
        struct sockaddr_storage saddr;
        socklen_t addrLen = sizeof(saddr);
        if (getpeername(fd, (struct sockaddr *)&saddr, &addrLen) == 0) {
            uint32_t ip = 0;
            if (saddr.ss_family == AF_INET) {
                ip = ntohl(((struct sockaddr_in *)&saddr)->sin_addr.s_addr);
            } else if (saddr.ss_family == AF_INET6) {
                // IPv4-mapped IPv6: ::ffff:x.x.x.x — last 4 bytes are the IPv4 address
                struct sockaddr_in6 *a6 = (struct sockaddr_in6 *)&saddr;
                uint8_t *b = a6->sin6_addr.s6_addr;
                if (b[10] == 0xFF && b[11] == 0xFF) {
                    ip = ((uint32_t)b[12] << 24) | ((uint32_t)b[13] << 16) |
                         ((uint32_t)b[14] << 8)  |  (uint32_t)b[15];
                }
            }
            // AP subnet: 192.168.4.0/24 = 0xC0A80400
            if (ip && (ip & 0xFFFFFF00) == 0xC0A80400) {
                return handleRecoveryPage(req);
            }
        }
    }

    return sendGzipPage(req, web_ui_html_gz_start,
                        (size_t)(web_ui_html_gz_end - web_ui_html_gz_start));
}

esp_err_t WebUI::handleRecoveryPage(httpd_req_t *req) {
    return sendGzipPage(req, recovery_html_gz_start,
                        (size_t)(recovery_html_gz_end - recovery_html_gz_start));
}

static constexpr char AP_REDIRECT_URL[] = "http://192.168.4.1:8080/";

static void doRedirect(httpd_req_t *req) {
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", AP_REDIRECT_URL);
    httpd_resp_sendstr(req, "Redirecting...");
}

esp_err_t WebUI::handleRedirect80(httpd_req_t *req) {
    doRedirect(req);
    return ESP_OK;
}

static esp_err_t handleRedirect404(httpd_req_t *req, httpd_err_code_t) {
    doRedirect(req);
    return ESP_OK;
}

// ══════════════════════════════════════════════════════════════════════════════
// WiFi status and setup handlers
// ══════════════════════════════════════════════════════════════════════════════

esp_err_t WebUI::handleWifiStatus(httpd_req_t *req) {
    // Load cached SSID from NVS
    char ssid[33] = "";
    char pass[65] = "";
    WifiManager::loadCredentials(ssid, sizeof(ssid), pass, sizeof(pass));

    const DeviceSettings &cfg = settings.get();
    bool connected = WifiManager::isConnected();

    char escSSID[67], escName[65];
    jsonEscape(ssid, escSSID, sizeof(escSSID));
    jsonEscape(cfg.deviceName, escName, sizeof(escName));

    char buf[200];
    snprintf(buf, sizeof(buf),
        "{\"ssid\":\"%s\",\"deviceName\":\"%s\",\"connected\":%s}",
        escSSID, escName, connected ? "true" : "false");

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, buf);
    return ESP_OK;
}

bool WebUI::applyWifiCredentials(const char *json, const char **outError) {
    char ssid[33] = {0};
    char password[65] = {0};
    if (!jsonGetString(json, "ssid", ssid, sizeof(ssid)) || strlen(ssid) == 0) {
        *outError = "SSID is required";
        return false;
    }
    if (!jsonGetString(json, "password", password, sizeof(password)) || strlen(password) == 0) {
        *outError = "Password is required";
        return false;
    }
    LOG_INFO("[WebUI] Saving WiFi credentials (SSID: %s)", ssid);
    // Mark change pending in settings (for WiFi recovery shorter timeout)
    settings.get().wifiChangePending = true;
    settings.save();
    // Connect via WifiManager (saves to NVS and initiates connection)
    WifiManager::connect(ssid, password);
    return true;
}

esp_err_t WebUI::handleWifiSetup(httpd_req_t *req) {
    char body[150] = {0};
    int received = httpd_req_recv(req, body, sizeof(body) - 1);
    if (received <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Empty request");
        return ESP_FAIL;
    }
    body[received] = '\0';

    const char *error = nullptr;
    if (!webUI.applyWifiCredentials(body, &error)) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, error);
        return ESP_FAIL;
    }

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"saved\"}");
    return ESP_OK;
}

// ══════════════════════════════════════════════════════════════════════════════
// AP mode (captive portal redirect server on port 80)
// ══════════════════════════════════════════════════════════════════════════════

void WebUI::setAPMode(bool active) {
    if (active == _apMode) return;
    _apMode = active;

    if (active && !_redirectServer) {
        // Start lightweight HTTP server on port 80 for captive portal redirect
        httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
        cfg.server_port = 80;
        cfg.ctrl_port   = 32770;
        cfg.stack_size  = 4096;
        cfg.max_open_sockets = 2;
        cfg.lru_purge_enable = true;
        if (httpd_start(&_redirectServer, &cfg) == ESP_OK) {
            // Catch root
            const httpd_uri_t rUri = {
                .uri = "/", .method = HTTP_GET, .handler = handleRedirect80,
                .user_ctx = this, .is_websocket = false,
                .handle_ws_control_frames = false, .supported_subprotocol = NULL
            };
            httpd_register_uri_handler(_redirectServer, &rUri);
            // Catch all other URIs (OS captive portal checks: /generate_204, /connecttest.txt, etc.)
            httpd_register_err_handler(_redirectServer, HTTPD_404_NOT_FOUND, handleRedirect404);
            LOG_INFO("[WebUI] Port 80 captive portal server started");
        }
    } else if (!active && _redirectServer) {
        httpd_stop(_redirectServer);
        _redirectServer = NULL;
        LOG_INFO("[WebUI] Port 80 redirect server stopped");
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// PWA manifest and icon handlers
// ══════════════════════════════════════════════════════════════════════════════

static const char MANIFEST_JSON[] =
    "{\"name\":\"" BRAND_NAME "\""
    ",\"short_name\":\"" BRAND_NAME "\""
    ",\"start_url\":\"/\""
    ",\"display\":\"standalone\""
    ",\"background_color\":\"#121220\""
    ",\"theme_color\":\"" BRAND_THEME_COLOR "\""
    ",\"icons\":["
    "{\"src\":\"/icon-192.png\",\"sizes\":\"192x192\",\"type\":\"image/png\"}"
    ",{\"src\":\"/icon-512.png\",\"sizes\":\"512x512\",\"type\":\"image/png\"}"
    "]}";

esp_err_t WebUI::handleManifest(httpd_req_t *req) {
    httpd_resp_set_type(req, "application/manifest+json");
    httpd_resp_sendstr(req, MANIFEST_JSON);
    return ESP_OK;
}

esp_err_t WebUI::handleIcon192(httpd_req_t *req) {
    httpd_resp_set_type(req, "image/png");
    httpd_resp_send(req, (const char *)icon_192_png_start,
                    (ssize_t)(icon_192_png_end - icon_192_png_start));
    return ESP_OK;
}

esp_err_t WebUI::handleIcon512(httpd_req_t *req) {
    httpd_resp_set_type(req, "image/png");
    httpd_resp_send(req, (const char *)icon_512_png_start,
                    (ssize_t)(icon_512_png_end - icon_512_png_start));
    return ESP_OK;
}

// ══════════════════════════════════════════════════════════════════════════════
// begin() — start HTTP server on port 8080
// ══════════════════════════════════════════════════════════════════════════════

void WebUI::begin(CN105Controller *ctrl) {
    _ctrl = ctrl;

    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.server_port    = 8080;
    config.ctrl_port      = 32769;  // Different from default to avoid conflict
    config.stack_size     = 8192;   // Default 4096 too small for WS handlers + log buffers
    config.max_open_sockets = 4;
    config.lru_purge_enable = true;

    LOG_INFO("[WebUI] Starting HTTP server on port %d", config.server_port);

    esp_err_t ret = httpd_start(&_server, &config);
    if (ret != ESP_OK) {
        LOG_ERROR("[WebUI] Failed to start HTTP server: %d", ret);
        return;
    }

    // Register GET / handler (serve HTML)
    const httpd_uri_t rootUri = {
        .uri       = "/",
        .method    = HTTP_GET,
        .handler   = handleRoot,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &rootUri);

    // Register POST /upload handler (OTA firmware upload)
    const httpd_uri_t otaUri = {
        .uri       = "/upload",
        .method    = HTTP_POST,
        .handler   = handleOtaUpload,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &otaUri);

    // Register GET /ws handler (WebSocket)
    const httpd_uri_t wsUri = {
        .uri       = "/ws",
        .method    = HTTP_GET,
        .handler   = handleWebSocket,
        .user_ctx  = this,
        .is_websocket = true,
        .handle_ws_control_frames = true,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wsUri);

    // Register GET /wifi-status handler
    const httpd_uri_t wifiStatusUri = {
        .uri       = "/wifi-status",
        .method    = HTTP_GET,
        .handler   = handleWifiStatus,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wifiStatusUri);

    // Register POST /wifi-setup handler
    const httpd_uri_t wifiSetupUri = {
        .uri       = "/wifi-setup",
        .method    = HTTP_POST,
        .handler   = handleWifiSetup,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wifiSetupUri);

    // Register PWA manifest and icon handlers
    const httpd_uri_t manifestUri = {
        .uri = "/manifest.json", .method = HTTP_GET, .handler = handleManifest,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &manifestUri);

    const httpd_uri_t icon192Uri = {
        .uri = "/icon-192.png", .method = HTTP_GET, .handler = handleIcon192,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &icon192Uri);

    const httpd_uri_t icon512Uri = {
        .uri = "/icon-512.png", .method = HTTP_GET, .handler = handleIcon512,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &icon512Uri);

    LOG_INFO("[WebUI] HTTP server started, WebSocket endpoint at /ws");

    // Register log hook to stream logs to WebSocket client
    logHook = [](const char *msg, size_t len) { webUI.broadcastLog(msg, len); };
}
