#include "web_server.h"
#include "json_utils.h"
#include "event_log.h"
#include "branding.h"
#include "wifi_manager.h"
#include "wifi_recovery.h"
#include "homekit_setup.h"
#include "logging.h"
#include <cstring>
#include <cstdio>
#include <lwip/sockets.h>
#include <array>
#include "esp_rom_crc.h"

static const char *TAG = "web";

// Disable Nagle on every new connection — eliminates up-to-200ms delay on small
// writes (WebSocket state pushes, log lines).  Called by esp_http_server via open_fn.
static esp_err_t setTcpNoDelay(httpd_handle_t, int sockfd) {
    int flag = 1;
    setsockopt(sockfd, IPPROTO_TCP, TCP_NODELAY, &flag, sizeof(flag));
    LOG_DEBUG("HTTP: new connection accepted (fd=%d)", sockfd);
    return ESP_OK;
}

// ── Embedded binary assets (generated by CMake target_add_binary_data) ──────
extern const uint8_t web_ui_html_gz_start[] asm("_binary_web_ui_html_gz_start");
extern const uint8_t web_ui_html_gz_end[]   asm("_binary_web_ui_html_gz_end");
extern const uint8_t recovery_html_gz_start[] asm("_binary_recovery_html_gz_start");
extern const uint8_t recovery_html_gz_end[]   asm("_binary_recovery_html_gz_end");
extern const uint8_t icon_192_png_start[] asm("_binary_icon_192_png_start");
extern const uint8_t icon_192_png_end[]   asm("_binary_icon_192_png_end");
extern const uint8_t icon_512_png_start[] asm("_binary_icon_512_png_start");
extern const uint8_t icon_512_png_end[]   asm("_binary_icon_512_png_end");
extern const uint8_t favicon_png_start[]  asm("_binary_favicon_png_start");
extern const uint8_t favicon_png_end[]    asm("_binary_favicon_png_end");

// ── Content-derived ETag — CRC32 of the embedded assets, so it changes exactly
//    when they do. (A __DATE__/__TIME__ stamp goes stale: an OTA that only
//    changes the HTML doesn't recompile this file, so browsers would keep the
//    old page via 304.) Computed once on first use; magic-static is thread-safe.
static const char* assetEtag() {
    static const auto etag = [] {
        uint32_t crc = 0;
        crc = esp_rom_crc32_le(crc, web_ui_html_gz_start,   (uint32_t)(web_ui_html_gz_end   - web_ui_html_gz_start));
        crc = esp_rom_crc32_le(crc, recovery_html_gz_start, (uint32_t)(recovery_html_gz_end - recovery_html_gz_start));
        crc = esp_rom_crc32_le(crc, icon_192_png_start,     (uint32_t)(icon_192_png_end     - icon_192_png_start));
        crc = esp_rom_crc32_le(crc, icon_512_png_start,     (uint32_t)(icon_512_png_end     - icon_512_png_start));
        crc = esp_rom_crc32_le(crc, favicon_png_start,      (uint32_t)(favicon_png_end      - favicon_png_start));
        std::array<char, 12> e{};
        snprintf(e.data(), e.size(), "\"%08lx\"", (unsigned long)crc);
        return e;
    }();
    return etag.data();
}

// Return true (and send 304) if the client already has the current version
static bool sendNotModified(httpd_req_t *req) {
    char buf[64];
    if (httpd_req_get_hdr_value_str(req, "If-None-Match", buf, sizeof(buf)) == ESP_OK &&
        strcmp(buf, assetEtag()) == 0) {
        httpd_resp_set_status(req, "304 Not Modified");
        httpd_resp_send(req, NULL, 0);
        return true;
    }
    return false;
}

// ── Global instance ──────────────────────────────────────────────────────────
WebUI webUI;

// ══════════════════════════════════════════════════════════════════════════════
// HTTP handler: GET /  (serve embedded gzipped HTML)
// ══════════════════════════════════════════════════════════════════════════════

esp_err_t WebUI::sendGzipPage(httpd_req_t *req, const uint8_t *data, size_t len) {
    if (sendNotModified(req)) return ESP_OK;
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    httpd_resp_set_hdr(req, "ETag", assetEtag());
    httpd_resp_send(req, (const char *)data, len);
    return ESP_OK;
}

// True if the request's peer is on the fallback AP subnet (192.168.4.0/24).
static bool isApSubnetClient(httpd_req_t *req) {
    int fd = httpd_req_to_sockfd(req);
    struct sockaddr_storage saddr;
    socklen_t addrLen = sizeof(saddr);
    if (getpeername(fd, (struct sockaddr *)&saddr, &addrLen) != 0) return false;
    uint32_t ip = 0;
    if (saddr.ss_family == AF_INET) {
        ip = ntohl(((struct sockaddr_in *)&saddr)->sin_addr.s_addr);
    } else if (saddr.ss_family == AF_INET6) {
        // IPv4-mapped IPv6: ::ffff:x.x.x.x — last 4 bytes are the IPv4 address
        struct sockaddr_in6 *a6 = (struct sockaddr_in6 *)&saddr;
        uint8_t *b = a6->sin6_addr.s6_addr;
        if (b[10] == 0xFF && b[11] == 0xFF) {
            ip = ((uint32_t)b[12] << 24) | ((uint32_t)b[13] << 16) |
                 ((uint32_t)b[14] << 8)  |  (uint32_t)b[15];
        }
    }
    // AP subnet: 192.168.4.0/24 = 0xC0A80400
    return ip && (ip & 0xFFFFFF00) == 0xC0A80400;
}

esp_err_t WebUI::handleRoot(httpd_req_t *req) {
    // If AP fallback is active and the client is on the AP subnet, serve the
    // WiFi setup page instead of the main UI.
    if (webUI._apMode && isApSubnetClient(req)) {
        return handleRecoveryPage(req);
    }

    return sendGzipPage(req, web_ui_html_gz_start,
                        (size_t)(web_ui_html_gz_end - web_ui_html_gz_start));
}

esp_err_t WebUI::handleRecoveryPage(httpd_req_t *req) {
    return sendGzipPage(req, recovery_html_gz_start,
                        (size_t)(recovery_html_gz_end - recovery_html_gz_start));
}

// ── CNA (Captive Network Assistant) detection page ──────────────────────────
// Served on port 80 to trigger captive portal popups on iOS/macOS/Android/Windows.
// Returns 200 with HTML (not 302) so all platforms detect the captive portal.
static const char CNA_PAGE[] =
    "<!DOCTYPE html><html><head>"
    "<meta http-equiv=\"refresh\" content=\"0;url=http://192.168.4.1/\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>WiFi Setup</title>"
    "<style>body{font-family:-apple-system,system-ui,sans-serif;background:#000;"
    "color:#fff;display:flex;justify-content:center;align-items:center;"
    "min-height:100vh;margin:0;text-align:center}"
    "a{color:#007AFF;font-size:17px;text-decoration:none}</style>"
    "</head><body><div>"
    "<p style=\"font-size:15px;color:#8E8E93;margin-bottom:16px\">"
    "Redirecting to WiFi setup&hellip;</p>"
    "<a href=\"http://192.168.4.1/\">Tap here if not redirected</a>"
    "</div></body></html>";

static void serveCNAPage(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    httpd_resp_sendstr(req, CNA_PAGE);
}

// Catch-all 404 handler installed only while the fallback AP is active. Serves
// the captive-portal page to AP-subnet clients (triggers the OS popup); any
// other client gets a normal 404 so the main UI behaves normally.
static esp_err_t handleRedirect404(httpd_req_t *req, httpd_err_code_t) {
    if (webUI.isAPMode() && isApSubnetClient(req)) {
        serveCNAPage(req);
        return ESP_OK;
    }
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Not found");
    return ESP_FAIL;
}

// ══════════════════════════════════════════════════════════════════════════════
// WiFi status and setup handlers
// ══════════════════════════════════════════════════════════════════════════════

esp_err_t WebUI::handleWifiStatus(httpd_req_t *req) {
    // Load cached SSID from NVS
    char ssid[33] = "";
    char pass[65] = "";
    WifiManager::loadCredentials(ssid, sizeof(ssid), pass, sizeof(pass));

    const DeviceSettings &cfg = settings.get();
    bool connected = WifiManager::isConnected();

    char escSSID[67], escName[65];
    jsonEscape(ssid, escSSID, sizeof(escSSID));
    jsonEscape(cfg.deviceName, escName, sizeof(escName));

    // "joined" = connected on the credentials last applied. The bare
    // connected level stays true for the OLD network throughout a
    // dial-initiated change window — the page's join poll must not key
    // success off it (on-device round 2, 2026-07-12).
    bool joined = connected && !WifiManager::isJoinPending();

    char buf[300];
    snprintf(buf, sizeof(buf),
        "{\"ssid\":\"%s\",\"deviceName\":\"%s\",\"connected\":%s"
        ",\"joined\":%s,\"hkSetupCode\":\"%s\"}",
        escSSID, escName, connected ? "true" : "false",
        joined ? "true" : "false",
        homekit_get_setup_code());

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, buf);
    return ESP_OK;
}

esp_err_t WebUI::handleWifiScan(httpd_req_t *req) {
    WifiManager::ScannedNetwork networks[15];
    int count = WifiManager::scanNetworks(networks, 15);

    char buf[1200];
    int pos = 0;
    jsonAppend(buf, sizeof(buf), &pos, "[");
    for (int i = 0; i < count; i++) {
        char escSSID[67];
        jsonEscape(networks[i].ssid, escSSID, sizeof(escSSID));
        jsonAppend(buf, sizeof(buf), &pos,
            "%s{\"ssid\":\"%s\",\"rssi\":%d,\"secure\":%s}",
            i > 0 ? "," : "",
            escSSID,
            (int)networks[i].rssi,
            networks[i].secure ? "true" : "false");
        if (pos >= (int)sizeof(buf) - 80) break;
    }
    jsonAppend(buf, sizeof(buf), &pos, "]");

    httpd_resp_set_type(req, "application/json");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store");
    httpd_resp_sendstr(req, buf);
    return ESP_OK;
}

bool WebUI::applyWifiCredentials(const char *json, const char **outError) {
    char ssid[33] = {0};
    char password[65] = {0};
    if (!jsonGetString(json, "ssid", ssid, sizeof(ssid)) || strlen(ssid) == 0) {
        *outError = "SSID is required";
        return false;
    }
    // Password is optional (open networks send empty password)
    jsonGetString(json, "password", password, sizeof(password));
    LOG_INFO("Saving WiFi credentials (SSID: %s)", ssid);
    eventlog_append(EV_WIFI_CREDS_CHANGED);
    // Connect via WifiManager (saves to NVS and initiates connection)
    WifiManager::connect(ssid, password);
    // Mark change pending (shorter recovery timeout); also refreshes the
    // cached SSID from the just-saved credentials
    wifiRecovery.setChangePending(true);
    // Let the change window close on join success (and stop treating STA
    // reconnects as old-network blips)
    wifiRecovery.noteReprovision();
    return true;
}

esp_err_t WebUI::handleWifiSetup(httpd_req_t *req) {
    char body[150] = {0};
    int received = httpd_req_recv(req, body, sizeof(body) - 1);
    if (received <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Empty request");
        return ESP_FAIL;
    }
    body[received] = '\0';

    const char *error = nullptr;
    if (!webUI.applyWifiCredentials(body, &error)) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, error);
        return ESP_FAIL;
    }

    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"saved\"}");
    return ESP_OK;
}

// ══════════════════════════════════════════════════════════════════════════════
// AP mode (captive portal handler on the port-80 web server)
// ══════════════════════════════════════════════════════════════════════════════

// The web UI now owns port 80, so the captive portal no longer needs a separate
// server: while the fallback AP is active we install a catch-all 404 handler on
// the main server that serves the captive-portal page to AP-subnet clients.
// handleRoot already routes AP-subnet clients to the WiFi setup page.
void WebUI::setAPMode(bool active) {
    if (active == _apMode) return;
    _apMode = active;
    applyCaptivePortalHandler();
}

void WebUI::applyCaptivePortalHandler() {
    if (!_server) return;  // begin() re-applies this once the server is up
    if (_apMode) {
        // Catch OS captive portal probes (/generate_204, /connecttest.txt, etc.)
        httpd_register_err_handler(_server, HTTPD_404_NOT_FOUND, handleRedirect404);
        LOG_INFO("Captive portal handler enabled (AP mode)");
    } else {
        httpd_register_err_handler(_server, HTTPD_404_NOT_FOUND, NULL);
        LOG_INFO("Captive portal handler disabled");
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// PWA manifest and icon handlers
// ══════════════════════════════════════════════════════════════════════════════

static const char MANIFEST_JSON[] =
    "{\"name\":\"" BRAND_NAME "\""
    ",\"short_name\":\"" BRAND_NAME "\""
    ",\"start_url\":\"/\""
    ",\"display\":\"standalone\""
    ",\"background_color\":\"#121220\""
    ",\"theme_color\":\"" BRAND_THEME_COLOR "\""
    ",\"icons\":["
    "{\"src\":\"/icon-192.png\",\"sizes\":\"192x192\",\"type\":\"image/png\"}"
    ",{\"src\":\"/icon-512.png\",\"sizes\":\"512x512\",\"type\":\"image/png\"}"
    "]}";

esp_err_t WebUI::handleManifest(httpd_req_t *req) {
    if (sendNotModified(req)) return ESP_OK;
    httpd_resp_set_type(req, "application/manifest+json");
    httpd_resp_set_hdr(req, "Cache-Control", "public, max-age=86400");
    httpd_resp_set_hdr(req, "ETag", assetEtag());
    httpd_resp_sendstr(req, MANIFEST_JSON);
    return ESP_OK;
}

esp_err_t WebUI::handleIcon192(httpd_req_t *req) {
    if (sendNotModified(req)) return ESP_OK;
    httpd_resp_set_type(req, "image/png");
    httpd_resp_set_hdr(req, "Cache-Control", "public, max-age=86400");
    httpd_resp_set_hdr(req, "ETag", assetEtag());
    httpd_resp_send(req, (const char *)icon_192_png_start,
                    (ssize_t)(icon_192_png_end - icon_192_png_start));
    return ESP_OK;
}

esp_err_t WebUI::handleIcon512(httpd_req_t *req) {
    if (sendNotModified(req)) return ESP_OK;
    httpd_resp_set_type(req, "image/png");
    httpd_resp_set_hdr(req, "Cache-Control", "public, max-age=86400");
    httpd_resp_set_hdr(req, "ETag", assetEtag());
    httpd_resp_send(req, (const char *)icon_512_png_start,
                    (ssize_t)(icon_512_png_end - icon_512_png_start));
    return ESP_OK;
}

esp_err_t WebUI::handleFavicon(httpd_req_t *req) {
    if (sendNotModified(req)) return ESP_OK;
    httpd_resp_set_type(req, "image/png");
    httpd_resp_set_hdr(req, "Cache-Control", "public, max-age=86400");
    httpd_resp_set_hdr(req, "ETag", assetEtag());
    httpd_resp_send(req, (const char *)favicon_png_start,
                    (ssize_t)(favicon_png_end - favicon_png_start));
    return ESP_OK;
}

// ══════════════════════════════════════════════════════════════════════════════
// begin() — start HTTP server on port 80
// ══════════════════════════════════════════════════════════════════════════════

void WebUI::begin(CN105Controller *ctrl) {
    _ctrl = ctrl;

    if (!_wsSendMux) _wsSendMux = xSemaphoreCreateMutex();
    if (!_wsSendMux) LOG_ERROR("WS send mutex alloc failed — WS output disabled");

    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.server_port      = 80;
    config.ctrl_port        = 32769;  // Different from default to avoid conflict
    config.stack_size       = 8192;   // Default 4096 too small for WS handlers + log buffers
    config.max_uri_handlers = 10;     // Default 8 too few for all endpoints
    config.max_open_sockets = 7;
    config.lru_purge_enable = true;
    config.open_fn          = setTcpNoDelay;

    LOG_INFO("Starting HTTP server on port %d", config.server_port);

    esp_err_t ret = httpd_start(&_server, &config);
    if (ret != ESP_OK) {
        LOG_ERROR("Failed to start HTTP server: %d", ret);
        return;
    }

    // Register GET / handler (serve HTML)
    const httpd_uri_t rootUri = {
        .uri       = "/",
        .method    = HTTP_GET,
        .handler   = handleRoot,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &rootUri);

    // Register POST /upload handler (OTA firmware upload)
    const httpd_uri_t otaUri = {
        .uri       = "/upload",
        .method    = HTTP_POST,
        .handler   = handleOtaUpload,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &otaUri);

    // Register GET /ws handler (WebSocket)
    const httpd_uri_t wsUri = {
        .uri       = "/ws",
        .method    = HTTP_GET,
        .handler   = handleWebSocket,
        .user_ctx  = this,
        .is_websocket = true,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wsUri);

    // Register GET /wifi-status handler
    const httpd_uri_t wifiStatusUri = {
        .uri       = "/wifi-status",
        .method    = HTTP_GET,
        .handler   = handleWifiStatus,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wifiStatusUri);

    // Register POST /wifi-setup handler
    const httpd_uri_t wifiSetupUri = {
        .uri       = "/wifi-setup",
        .method    = HTTP_POST,
        .handler   = handleWifiSetup,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wifiSetupUri);

    // Register GET /wifi-scan handler
    const httpd_uri_t wifiScanUri = {
        .uri       = "/wifi-scan",
        .method    = HTTP_GET,
        .handler   = handleWifiScan,
        .user_ctx  = this,
        .is_websocket = false,
        .handle_ws_control_frames = false,
        .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &wifiScanUri);

    // Register PWA manifest and icon handlers
    const httpd_uri_t manifestUri = {
        .uri = "/manifest.json", .method = HTTP_GET, .handler = handleManifest,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &manifestUri);

    const httpd_uri_t icon192Uri = {
        .uri = "/icon-192.png", .method = HTTP_GET, .handler = handleIcon192,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &icon192Uri);

    const httpd_uri_t icon512Uri = {
        .uri = "/icon-512.png", .method = HTTP_GET, .handler = handleIcon512,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &icon512Uri);

    const httpd_uri_t faviconUri = {
        .uri = "/favicon.png", .method = HTTP_GET, .handler = handleFavicon,
        .user_ctx = this, .is_websocket = false,
        .handle_ws_control_frames = false, .supported_subprotocol = NULL
    };
    httpd_register_uri_handler(_server, &faviconUri);

    // If the fallback AP was already active before the server came up, install
    // the captive portal handler now (setAPMode() may have run pre-begin()).
    applyCaptivePortalHandler();

    LOG_INFO("HTTP server started, WebSocket endpoint at /ws");
}
