#!/usr/bin/env python3
"""Gzip an HTML file and emit a C byte array header."""

import gzip
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

# Default paths (backward compatible)
DEFAULT_INPUT = os.path.join(PROJECT_ROOT, "web", "index.html")
DEFAULT_OUTPUT = os.path.join(PROJECT_ROOT, "include", "web_ui_html.h")


def embed(input_file, output_file, brand_vars=None):
    if not os.path.isfile(input_file):
        print(f"ERROR: {input_file} not found", file=sys.stderr)
        sys.exit(1)

    with open(input_file, "rb") as f:
        raw = f.read()

    # Template substitution: replace {{KEY}} with value
    if brand_vars:
        text = raw.decode("utf-8")
        for key, val in brand_vars.items():
            text = text.replace("{{" + key + "}}", val)
        raw = text.encode("utf-8")

    compressed = gzip.compress(raw, compresslevel=9)
    raw_size = len(raw)
    gz_size = len(compressed)

    # Derive variable name from output filename
    basename = os.path.splitext(os.path.basename(output_file))[0].upper()
    var_name = basename + "_GZ"
    len_name = basename + "_GZ_LEN"

    lines = []
    for i in range(0, gz_size, 16):
        chunk = compressed[i : i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals}")

    body = ",\n".join(lines)

    header = (
        "// Auto-generated by scripts/embed_html.py — do not edit\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "\n"
        f"// Source: {os.path.relpath(input_file, PROJECT_ROOT)} ({raw_size} bytes raw, {gz_size} bytes gzipped)\n"
        f"const uint8_t {var_name}[] PROGMEM = {{\n"
        f"{body}\n"
        "};\n"
        f"const size_t {len_name} = sizeof({var_name});\n"
    )

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w") as f:
        f.write(header)

    print(f"Embedded {input_file}")
    print(f"  Raw size:    {raw_size:,} bytes")
    print(f"  Gzipped:     {gz_size:,} bytes")
    print(f"  Ratio:       {gz_size / raw_size * 100:.1f}%")
    print(f"  Output:      {output_file}")


def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_INPUT
    output_file = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTPUT
    brand_vars = json.loads(sys.argv[3]) if len(sys.argv) > 3 else None
    embed(input_file, output_file, brand_vars)


if __name__ == "__main__":
    main()
