#!/usr/bin/env python3
"""Convert a binary file to a C PROGMEM byte array header."""

import os
import sys


def embed(input_file, output_file):
    if not os.path.isfile(input_file):
        print(f"ERROR: {input_file} not found", file=sys.stderr)
        sys.exit(1)

    with open(input_file, "rb") as f:
        data = f.read()

    size = len(data)
    basename = os.path.splitext(os.path.basename(output_file))[0].upper()
    var_name = basename
    len_name = basename + "_LEN"

    lines = []
    for i in range(0, size, 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals}")

    body = ",\n".join(lines)

    header = (
        "// Auto-generated by scripts/embed_binary.py — do not edit\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "\n"
        f"// Source: {os.path.basename(input_file)} ({size:,} bytes)\n"
        f"const uint8_t {var_name}[] PROGMEM = {{\n"
        f"{body}\n"
        "};\n"
        f"const size_t {len_name} = sizeof({var_name});\n"
    )

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w") as f:
        f.write(header)

    print(f"Embedded {input_file} ({size:,} bytes) -> {output_file}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_file> <output_header>", file=sys.stderr)
        sys.exit(1)
    embed(sys.argv[1], sys.argv[2])
